# Meta
description: 美麗的太陽照常升起 苦痛的人們依舊歇斯底裏
keywords: ios,objective-c,swift,python,javascript,otaku,lision
site_desc: otaku's self-cultivation

# Navigation
navigation:
- name: Home
  slug: home
  url: /
- name: Archives
  slug: archives
  url: /archives
- name: About
  slug: about
  url: https://github.com/Lision

# Search
search: 
  enable: true
  service: google # google/hexo/algolia/azure/baidu
  # google 
  google_api_key: AIzaSyAMIoydL742ROhE6lLk9n3hT0pZwbrXD_I
  google_engine_id: 001858749347000340533:drswradlp64
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Miscellaneous
google_analytics: UA-118743071-1
favicon: /favicon.png
author_url: https://lision.me

# Less
less:
  compress: true

# use url, not username
social:
- slug: email
  url: mailto:lisionmail@gmail.com
- slug: github
  url: https://github.com/Lision
- slug: twitter
  url: https://twitter.com/LisionChat
- slug: rss
	url: # /atom.xml
- slug: google
  url: # https://plus.google.com/+ArtChenOtakism/posts
- slug: facebook
  url: # https://www.facebook.com/zanchoret
- slug: linkedin
  url: # https://www.linkedin.com/in/buzun
- slug: sina-weibo
  url: https://weibo.com/lisioncode
- slug: tumblr
  url: # http://artchen.tumblr.com
- slug: dribbble
  url: # https://dribbble.com/artchen
- slug: pinterest
  url: # https://www.pinterest.com/otakism/
- slug: instagram
  url: # https://instagram.com/otakism/
- slug: behance
  url: # https://www.behance.net/artchen
